In [1]:
import pandas as pd

In [2]:
fund = pd.read_csv("fundamentals.csv")
fund.head()

,Unnamed: 0,Ticker Symbol,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding
0,0,AAL,2012-12-31,3.068000e+09,-222000000.0,-1.961000e+09,23.0,-1.888000e+09,4.695000e+09,53.0,...,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,2012.0,-5.60,3.350000e+08
1,1,AAL,2013-12-31,4.975000e+09,-93000000.0,-2.723000e+09,67.0,-3.114000e+09,1.059200e+10,75.0,...,1.432300e+10,1.380600e+10,-2.731000e+09,4.500900e+10,4.227800e+10,2.674300e+10,0.0,2013.0,-11.25,1.630222e+08
2,2,AAL,2014-12-31,4.668000e+09,-160000000.0,-1.500000e+08,143.0,-5.311000e+09,1.513500e+10,60.0,...,1.175000e+10,1.340400e+10,2.021000e+09,4.120400e+10,4.322500e+10,4.265000e+10,0.0,2014.0,4.02,7.169154e+08
3,3,AAL,2015-12-31,5.102000e+09,352000000.0,-7.080000e+08,135.0,-6.151000e+09,1.159100e+10,51.0,...,9.985000e+09,1.360500e+10,5.635000e+09,4.278000e+10,4.841500e+10,4.099000e+10,0.0,2015.0,11.39,6.681299e+08
4,4,AAP,2012-12-29,2.409453e+09,-89482000.0,6.000000e+05,32.0,-2.711820e+08,5.202150e+08,23.0,...,3.184200e+09,2.559638e+09,1.210694e+09,3.403120e+09,4.613814e+09,6.205003e+09,-27095000.0,2012.0,5.29,7.328355e+07

In [3]:
fund1 = pd.read_csv("fundamentals.csv",index_col="Ticker Symbol")
fund1.head()

,Unnamed: 0,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,Cash and Cash Equivalents,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding
Ticker Symbol,,,,,,,,,,,,,,,,,,,,,
AAL,0,2012-12-31,3.068000e+09,-222000000.0,-1.961000e+09,23.0,-1.888000e+09,4.695000e+09,53.0,1.330000e+09,...,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,2012.0,-5.60,3.350000e+08
AAL,1,2013-12-31,4.975000e+09,-93000000.0,-2.723000e+09,67.0,-3.114000e+09,1.059200e+10,75.0,2.175000e+09,...,1.432300e+10,1.380600e+10,-2.731000e+09,4.500900e+10,4.227800e+10,2.674300e+10,0.0,2013.0,-11.25,1.630222e+08
AAL,2,2014-12-31,4.668000e+09,-160000000.0,-1.500000e+08,143.0,-5.311000e+09,1.513500e+10,60.0,1.768000e+09,...,1.175000e+10,1.340400e+10,2.021000e+09,4.120400e+10,4.322500e+10,4.265000e+10,0.0,2014.0,4.02,7.169154e+08
AAL,3,2015-12-31,5.102000e+09,352000000.0,-7.080000e+08,135.0,-6.151000e+09,1.159100e+10,51.0,1.085000e+09,...,9.985000e+09,1.360500e+10,5.635000e+09,4.278000e+10,4.841500e+10,4.099000e+10,0.0,2015.0,11.39,6.681299e+08
AAP,4,2012-12-29,2.409453e+09,-89482000.0,6.000000e+05,32.0,-2.711820e+08,5.202150e+08,23.0,5.981110e+08,...,3.184200e+09,2.559638e+09,1.210694e+09,3.403120e+09,4.613814e+09,6.205003e+09,-27095000.0,2012.0,5.29,7.328355e+07

In [4]:
print (fund.columns)

Index(['Unnamed: 0', 'Ticker Symbol', 'Period Ending', 'Accounts Payable',
       'Accounts Receivable', 'Add'l income/expense items', 'After Tax ROE',
       'Capital Expenditures', 'Capital Surplus', 'Cash Ratio',
       'Cash and Cash Equivalents', 'Changes in Inventories', 'Common Stocks',
       'Cost of Revenue', 'Current Ratio', 'Deferred Asset Charges',
       'Deferred Liability Charges', 'Depreciation',
       'Earnings Before Interest and Tax', 'Earnings Before Tax',
       'Effect of Exchange Rate',
       'Equity Earnings/Loss Unconsolidated Subsidiary', 'Fixed Assets',
       'Goodwill', 'Gross Margin', 'Gross Profit', 'Income Tax',
       'Intangible Assets', 'Interest Expense', 'Inventory', 'Investments',
       'Liabilities', 'Long-Term Debt', 'Long-Term Investments',
       'Minority Interest', 'Misc. Stocks', 'Net Borrowings', 'Net Cash Flow',
       'Net Cash Flow-Operating', 'Net Cash Flows-Financing',
       'Net Cash Flows-Investing', 'Net Income', 'Net Income Adjustments',
       'Net Income Applicable to Common Shareholders',
       'Net Income-Cont. Operations', 'Net Receivables', 'Non-Recurring Items',
       'Operating Income', 'Operating Margin', 'Other Assets',
       'Other Current Assets', 'Other Current Liabilities', 'Other Equity',
       'Other Financing Activities', 'Other Investing Activities',
       'Other Liabilities', 'Other Operating Activities',
       'Other Operating Items', 'Pre-Tax Margin', 'Pre-Tax ROE',
       'Profit Margin', 'Quick Ratio', 'Research and Development',
       'Retained Earnings', 'Sale and Purchase of Stock',
       'Sales, General and Admin.',
       'Short-Term Debt / Current Portion of Long-Term Debt',
       'Short-Term Investments', 'Total Assets', 'Total Current Assets',
       'Total Current Liabilities', 'Total Equity', 'Total Liabilities',
       'Total Liabilities & Equity', 'Total Revenue', 'Treasury Stock',
       'For Year', 'Earnings Per Share', 'Estimated Shares Outstanding'],
      dtype='object')

In [5]:
fund[['Ticker Symbol','Total Revenue','Earnings Before Tax']]

     Ticker Symbol  Total Revenue  Earnings Before Tax
0              AAL   2.485500e+10        -2.445000e+09
1              AAL   2.674300e+10        -2.180000e+09
2              AAL   4.265000e+10         3.212000e+09
3              AAL   4.099000e+10         4.616000e+09
4              AAP   6.205003e+09         6.240740e+08
...            ...            ...                  ...
1776          ZION   2.210591e+09         4.518590e+08
1777           ZTS   4.561000e+09         6.900000e+08
1778           ZTS   4.785000e+09         8.200000e+08
1779           ZTS   4.765000e+09         5.450000e+08
1780           ZTS   4.888000e+09         1.228000e+09

[1781 rows x 3 columns]

In [6]:
aapl = fund1.loc[["AAPL"]]

In [7]:
aapl.columns

Index(['Unnamed: 0', 'Period Ending', 'Accounts Payable',
       'Accounts Receivable', 'Add'l income/expense items', 'After Tax ROE',
       'Capital Expenditures', 'Capital Surplus', 'Cash Ratio',
       'Cash and Cash Equivalents', 'Changes in Inventories', 'Common Stocks',
       'Cost of Revenue', 'Current Ratio', 'Deferred Asset Charges',
       'Deferred Liability Charges', 'Depreciation',
       'Earnings Before Interest and Tax', 'Earnings Before Tax',
       'Effect of Exchange Rate',
       'Equity Earnings/Loss Unconsolidated Subsidiary', 'Fixed Assets',
       'Goodwill', 'Gross Margin', 'Gross Profit', 'Income Tax',
       'Intangible Assets', 'Interest Expense', 'Inventory', 'Investments',
       'Liabilities', 'Long-Term Debt', 'Long-Term Investments',
       'Minority Interest', 'Misc. Stocks', 'Net Borrowings', 'Net Cash Flow',
       'Net Cash Flow-Operating', 'Net Cash Flows-Financing',
       'Net Cash Flows-Investing', 'Net Income', 'Net Income Adjustments',
       'Net Income Applicable to Common Shareholders',
       'Net Income-Cont. Operations', 'Net Receivables', 'Non-Recurring Items',
       'Operating Income', 'Operating Margin', 'Other Assets',
       'Other Current Assets', 'Other Current Liabilities', 'Other Equity',
       'Other Financing Activities', 'Other Investing Activities',
       'Other Liabilities', 'Other Operating Activities',
       'Other Operating Items', 'Pre-Tax Margin', 'Pre-Tax ROE',
       'Profit Margin', 'Quick Ratio', 'Research and Development',
       'Retained Earnings', 'Sale and Purchase of Stock',
       'Sales, General and Admin.',
       'Short-Term Debt / Current Portion of Long-Term Debt',
       'Short-Term Investments', 'Total Assets', 'Total Current Assets',
       'Total Current Liabilities', 'Total Equity', 'Total Liabilities',
       'Total Liabilities & Equity', 'Total Revenue', 'Treasury Stock',
       'For Year', 'Earnings Per Share', 'Estimated Shares Outstanding'],
      dtype='object')

In [8]:
aapl[['Earnings Before Tax','Total Equity']]

               Earnings Before Tax  Total Equity
Ticker Symbol
AAPL                  5.015500e+10  1.235490e+11
AAPL                  5.348300e+10  1.115470e+11
AAPL                  7.251500e+10  1.193550e+11
AAPL                  6.137200e+10  1.282490e+11

In [9]:
fund1['Earnings Per Share'].nsmallest(10)

Ticker Symbol
APA   -61.20
DVN   -35.55
XEC   -25.92
CHK   -22.43
NFX   -21.18
APA   -14.06
APC   -13.18
MUR   -13.03
FCX   -11.31
AAL   -11.25
Name: Earnings Per Share, dtype: float64

In [10]:
fund1['Total Revenue'] = fund1['Total Revenue'].astype('int')

In [11]:
fund1[fund1['Total Revenue']<1000000000]

,Unnamed: 0,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,Cash and Cash Equivalents,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding
Ticker Symbol,,,,,,,,,,,,,,,,,,,,,
AAL,0,2012-12-31,3.068000e+09,-222000000.0,-1.961000e+09,23.0,-1.888000e+09,4.695000e+09,53.0,1.330000e+09,...,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,-2147483648,-367000000.0,2012.0,-5.60,3.350000e+08
AAL,1,2013-12-31,4.975000e+09,-93000000.0,-2.723000e+09,67.0,-3.114000e+09,1.059200e+10,75.0,2.175000e+09,...,1.432300e+10,1.380600e+10,-2.731000e+09,4.500900e+10,4.227800e+10,-2147483648,0.0,2013.0,-11.25,1.630222e+08
AAL,2,2014-12-31,4.668000e+09,-160000000.0,-1.500000e+08,143.0,-5.311000e+09,1.513500e+10,60.0,1.768000e+09,...,1.175000e+10,1.340400e+10,2.021000e+09,4.120400e+10,4.322500e+10,-2147483648,0.0,2014.0,4.02,7.169154e+08
AAL,3,2015-12-31,5.102000e+09,352000000.0,-7.080000e+08,135.0,-6.151000e+09,1.159100e+10,51.0,1.085000e+09,...,9.985000e+09,1.360500e+10,5.635000e+09,4.278000e+10,4.841500e+10,-2147483648,0.0,2015.0,11.39,6.681299e+08
AAP,4,2012-12-29,2.409453e+09,-89482000.0,6.000000e+05,32.0,-2.711820e+08,5.202150e+08,23.0,5.981110e+08,...,3.184200e+09,2.559638e+09,1.210694e+09,3.403120e+09,4.613814e+09,-2147483648,-27095000.0,2012.0,5.29,7.328355e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZION,1776,2015-12-31,0.000000e+00,0.0,-2.530000e+06,4.0,-1.573610e+08,0.000000e+00,NaN,1.576313e+10,...,0.000000e+00,0.000000e+00,7.507519e+09,5.216201e+10,5.966952e+10,-2147483648,0.0,2015.0,1.20,2.578925e+08
ZTS,1777,2013-12-31,1.381000e+09,-99000000.0,9.000000e+06,54.0,-1.840000e+08,8.780000e+08,43.0,6.100000e+08,...,3.357000e+09,1.415000e+09,9.400000e+08,5.618000e+09,6.558000e+09,-2147483648,0.0,2013.0,1.01,4.990099e+08
ZTS,1778,2014-12-31,1.071000e+09,69000000.0,-7.000000e+06,44.0,-1.800000e+08,9.580000e+08,81.0,8.820000e+08,...,3.465000e+09,1.086000e+09,1.311000e+09,5.277000e+09,6.588000e+09,-2147483648,0.0,2014.0,1.16,5.025862e+08
ZTS,1779,2015-12-31,1.313000e+09,-58000000.0,-8.100000e+07,32.0,-2.240000e+08,1.012000e+09,65.0,1.154000e+09,...,3.830000e+09,1.781000e+09,1.068000e+09,6.845000e+09,7.913000e+09,-2147483648,-203000000.0,2015.0,0.68,4.985294e+08
ZTS,1780,2016-12-31,1.076000e+09,15000000.0,2.000000e+06,55.0,-2.160000e+08,1.024000e+09,65.0,7.270000e+08,...,3.390000e+09,1.117000e+09,1.487000e+09,6.162000e+09,7.649000e+09,-2147483648,-421000000.0,NaN,NaN,NaN

In [12]:
fund1[fund1['Total Revenue']>=1000000000]
fund1[(fund1['Total Revenue']>=1000000000) &(fund1['Total Revenue']<=10000000000)]

,Unnamed: 0,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,Cash and Cash Equivalents,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding
Ticker Symbol,,,,,,,,,,,,,,,,,,,,,
AKAM,72,2012-12-31,176378000.0,-2108000.0,7104000.0,9.0,-1.667730e+08,5.195543e+09,216.0,201989000.0,...,7.283840e+08,202944000.0,2.345754e+09,2.548730e+08,2.600627e+09,1373947000,-6.244620e+08,2012.0,1.15,1.773817e+08
AKAM,73,2013-12-31,224095000.0,-67184000.0,5586000.0,11.0,-1.879640e+08,4.561929e+09,256.0,333891000.0,...,1.029714e+09,263166000.0,2.629431e+09,3.282540e+08,2.957685e+09,1577922000,0.000000e+00,2013.0,1.65,1.778709e+08
AKAM,74,2014-12-31,282098000.0,-58397000.0,5720000.0,11.0,-2.071590e+08,4.559430e+09,227.0,238650000.0,...,1.262555e+09,334011000.0,2.945335e+09,1.056211e+09,4.001546e+09,1963874000,0.000000e+00,2014.0,1.87,1.785818e+08
ALLE,88,2013-12-31,418500000.0,27900000.0,-7200000.0,49.0,-2.020000e+07,2.850000e+07,55.0,267600000.0,...,9.468000e+08,490500000.0,-6.610000e+07,2.066700e+09,2.000600e+09,2069600000,0.000000e+00,NaN,NaN,NaN
ALLE,89,2014-12-31,379400000.0,-8000000.0,-4600000.0,3650.0,-5.150000e+07,0.000000e+00,55.0,290500000.0,...,1.001700e+09,532500000.0,-4.800000e+06,2.020700e+09,2.015900e+09,2118300000,0.000000e+00,2014.0,1.82,9.626374e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WAT,1672,2014-12-31,141311000.0,-29435000.0,7023000.0,23.0,-9.112200e+07,1.392494e+09,354.0,422177000.0,...,2.817044e+09,580486000.0,1.894666e+09,1.980024e+09,3.874690e+09,1989344000,-3.815203e+09,2014.0,NaN,NaN
WAT,1673,2015-12-31,153469000.0,-49888000.0,10711000.0,23.0,-1.000120e+08,1.490342e+09,425.0,487665000.0,...,3.213533e+09,564076000.0,2.058851e+09,2.209826e+09,4.268677e+09,2042332000,-4.149908e+09,2015.0,5.70,8.229000e+07
XEC,1729,2012-12-31,630377000.0,56435000.0,3895000.0,10.0,-1.727694e+09,1.939628e+09,11.0,69538000.0,...,4.701370e+08,645862000.0,3.474736e+09,2.830416e+09,6.305152e+09,1623938000,0.000000e+00,2012.0,4.08,8.672132e+07
XEC,1730,2013-12-31,647586000.0,-64780000.0,21309000.0,14.0,-1.624201e+09,1.970113e+09,1.0,4531000.0,...,4.691390e+08,683167000.0,4.022208e+09,3.230927e+09,7.253135e+09,1998051000,0.000000e+00,2013.0,6.48,8.714336e+07
XEC,1732,2015-12-31,396636000.0,186699000.0,24822000.0,86.0,-1.049636e+09,2.762976e+09,190.0,779382000.0,...,1.077930e+09,410067000.0,2.797678e+09,2.445608e+09,5.243286e+09,1452619000,0.000000e+00,2015.0,-25.92,9.293781e+07

In [13]:
fund1['Total Revenue'].nlargest(10)

Ticker Symbol
MCHP    2147036000
SRCL    2142807000
BXP     2135539000
ISRG    2131700000
ALLE    2118300000
PKI     2105188000
PG      2104745000
REGN    2104745000
AYI     2089100000
EFX     2073000000
Name: Total Revenue, dtype: int32

In [16]:
fund.isnull()

,Unnamed: 0,Ticker Symbol,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1776,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1777,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1778,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1779,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1780,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True

In [17]:
fund.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1781 entries, 0 to 1780
Data columns (total 79 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Unnamed: 0                                           1781 non-null   int64
 1   Ticker Symbol                                        1781 non-null   object
 2   Period Ending                                        1781 non-null   object
 3   Accounts Payable                                     1781 non-null   float64
 4   Accounts Receivable                                  1781 non-null   float64
 5   Add'l income/expense items                           1781 non-null   float64
 6   After Tax ROE                                        1781 non-null   float64
 7   Capital Expenditures                                 1781 non-null   float64
 8   Capital Surplus                                      1781 non-null   float64
 9   Cash Ratio                                           1482 non-null   float64
 10  Cash and Cash Equivalents                            1781 non-null   float64
 11  Changes in Inventories                               1781 non-null   float64
 12  Common Stocks                                        1781 non-null   float64
 13  Cost of Revenue                                      1781 non-null   float64
 14  Current Ratio                                        1482 non-null   float64
 15  Deferred Asset Charges                               1781 non-null   float64
 16  Deferred Liability Charges                           1781 non-null   float64
 17  Depreciation                                         1781 non-null   float64
 18  Earnings Before Interest and Tax                     1781 non-null   float64
 19  Earnings Before Tax                                  1781 non-null   float64
 20  Effect of Exchange Rate                              1781 non-null   float64
 21  Equity Earnings/Loss Unconsolidated Subsidiary       1781 non-null   float64
 22  Fixed Assets                                         1781 non-null   float64
 23  Goodwill                                             1781 non-null   float64
 24  Gross Margin                                         1781 non-null   float64
 25  Gross Profit                                         1781 non-null   float64
 26  Income Tax                                           1781 non-null   float64
 27  Intangible Assets                                    1781 non-null   float64
 28  Interest Expense                                     1781 non-null   float64
 29  Inventory                                            1781 non-null   float64
 30  Investments                                          1781 non-null   float64
 31  Liabilities                                          1781 non-null   float64
 32  Long-Term Debt                                       1781 non-null   float64
 33  Long-Term Investments                                1781 non-null   float64
 34  Minority Interest                                    1781 non-null   float64
 35  Misc. Stocks                                         1781 non-null   float64
 36  Net Borrowings                                       1781 non-null   float64
 37  Net Cash Flow                                        1781 non-null   float64
 38  Net Cash Flow-Operating                              1781 non-null   float64
 39  Net Cash Flows-Financing                             1781 non-null   float64
 40  Net Cash Flows-Investing                             1781 non-null   float64
 41  Net Income                                           1781 non-null   float64
 42  Net Income Adjustments                               1781 non-null   float64
 43  Net Income Applicable to Common Shareholders         1781 non-null   float64
 44  Net Income-Cont. Operations                          1781 non-null   float64
 45  Net Receivables                                      1781 non-null   float64
 46  Non-Recurring Items                                  1781 non-null   float64
 47  Operating Income                                     1781 non-null   float64
 48  Operating Margin                                     1781 non-null   float64
 49  Other Assets                                         1781 non-null   float64
 50  Other Current Assets                                 1781 non-null   float64
 51  Other Current Liabilities                            1781 non-null   float64
 52  Other Equity                                         1781 non-null   float64
 53  Other Financing Activities                           1781 non-null   float64
 54  Other Investing Activities                           1781 non-null   float64
 55  Other Liabilities                                    1781 non-null   float64
 56  Other Operating Activities                           1781 non-null   float64
 57  Other Operating Items                                1781 non-null   float64
 58  Pre-Tax Margin                                       1781 non-null   float64
 59  Pre-Tax ROE                                          1781 non-null   float64
 60  Profit Margin                                        1781 non-null   float64
 61  Quick Ratio                                          1482 non-null   float64
 62  Research and Development                             1781 non-null   float64
 63  Retained Earnings                                    1781 non-null   float64
 64  Sale and Purchase of Stock                           1781 non-null   float64
 65  Sales, General and Admin.                            1781 non-null   float64
 66  Short-Term Debt / Current Portion of Long-Term Debt  1781 non-null   float64
 67  Short-Term Investments                               1781 non-null   float64
 68  Total Assets                                         1781 non-null   float64
 69  Total Current Assets                                 1781 non-null   float64
 70  Total Current Liabilities                            1781 non-null   float64
 71  Total Equity                                         1781 non-null   float64
 72  Total Liabilities                                    1781 non-null   float64
 73  Total Liabilities & Equity                           1781 non-null   float64
 74  Total Revenue                                        1781 non-null   float64
 75  Treasury Stock                                       1781 non-null   float64
 76  For Year                                             1608 non-null   float64
 77  Earnings Per Share                                   1562 non-null   float64
 78  Estimated Shares Outstanding                         1562 non-null   float64
dtypes: float64(76), int64(1), object(2)
memory usage: 1.1+ MB

In [18]:
fund.dropna()

,Unnamed: 0,Ticker Symbol,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding
0,0,AAL,2012-12-31,3.068000e+09,-222000000.0,-1.961000e+09,23.0,-1.888000e+09,4.695000e+09,53.0,...,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-3.670000e+08,2012.0,-5.60,3.350000e+08
1,1,AAL,2013-12-31,4.975000e+09,-93000000.0,-2.723000e+09,67.0,-3.114000e+09,1.059200e+10,75.0,...,1.432300e+10,1.380600e+10,-2.731000e+09,4.500900e+10,4.227800e+10,2.674300e+10,0.000000e+00,2013.0,-11.25,1.630222e+08
2,2,AAL,2014-12-31,4.668000e+09,-160000000.0,-1.500000e+08,143.0,-5.311000e+09,1.513500e+10,60.0,...,1.175000e+10,1.340400e+10,2.021000e+09,4.120400e+10,4.322500e+10,4.265000e+10,0.000000e+00,2014.0,4.02,7.169154e+08
3,3,AAL,2015-12-31,5.102000e+09,352000000.0,-7.080000e+08,135.0,-6.151000e+09,1.159100e+10,51.0,...,9.985000e+09,1.360500e+10,5.635000e+09,4.278000e+10,4.841500e+10,4.099000e+10,0.000000e+00,2015.0,11.39,6.681299e+08
4,4,AAP,2012-12-29,2.409453e+09,-89482000.0,6.000000e+05,32.0,-2.711820e+08,5.202150e+08,23.0,...,3.184200e+09,2.559638e+09,1.210694e+09,3.403120e+09,4.613814e+09,6.205003e+09,-2.709500e+07,2012.0,5.29,7.328355e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1771,1771,ZBH,2014-12-31,2.255000e+08,-40400000.0,-3.480000e+07,11.0,-3.423000e+08,4.330700e+09,166.0,...,4.313300e+09,1.024000e+09,6.549900e+09,3.108100e+09,9.658000e+09,4.673300e+09,-6.183700e+09,2014.0,4.26,1.690845e+08
1772,1772,ZBH,2015-12-31,4.320000e+08,-56100000.0,-2.750000e+07,1.0,-4.341000e+08,8.195300e+09,100.0,...,5.862900e+09,1.617900e+09,9.887900e+09,1.733160e+10,2.721950e+10,5.997800e+09,-6.329100e+09,2015.0,0.78,1.884615e+08
1777,1777,ZTS,2013-12-31,1.381000e+09,-99000000.0,9.000000e+06,54.0,-1.840000e+08,8.780000e+08,43.0,...,3.357000e+09,1.415000e+09,9.400000e+08,5.618000e+09,6.558000e+09,4.561000e+09,0.000000e+00,2013.0,1.01,4.990099e+08
1778,1778,ZTS,2014-12-31,1.071000e+09,69000000.0,-7.000000e+06,44.0,-1.800000e+08,9.580000e+08,81.0,...,3.465000e+09,1.086000e+09,1.311000e+09,5.277000e+09,6.588000e+09,4.785000e+09,0.000000e+00,2014.0,1.16,5.025862e+08
1779,1779,ZTS,2015-12-31,1.313000e+09,-58000000.0,-8.100000e+07,32.0,-2.240000e+08,1.012000e+09,65.0,...,3.830000e+09,1.781000e+09,1.068000e+09,6.845000e+09,7.913000e+09,4.765000e+09,-2.030000e+08,2015.0,0.68,4.985294e+08